name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "*"

jobs:
  ci-cd:
    uses: EasyDesk/microservice-cicd/.github/workflows/microservice-cicd.yml@v0
    with:
      dotnet-version: 6.x
      warnings-as-errors: true
      main-project-name: src/EScooter.RentService.Web
      unit-test-project-name: test/EScooter.RentService.UnitTests
      app-publish-dir: app
      sql-script-name: update-database.sql
      artifact-name: build-artifacts
      release-prefix: EScooter.RentService
  deploy:
    uses: EasyDesk/microservice-azure-deploy/.github/workflows/microservice-azure-deploy.yml@v0
    name: Deploy to Production environment
    needs: [ci-cd]
    if: needs.ci-cd.outputs.released == 'true'
    with:
      artifact-name: build-artifacts
      resource-group: e-scooter
      app-name: escooter-rent-service
      publish-dir: app
      migrations-script: update-database.sql
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
      db-server-name: ${{ secrets.DB_SERVER }}
      db-connection-string: ${{ secrets.DB_CONNECTION_STRING }}
